const filterCategory = [
  {
    type: "Tingkat",
    categories: ["Universitas", "Pra-Kampus"],
  },
  {
    type: "Tipe",
    categories: ["Kepanitiaan", "Organisasi", "UKM"],
  },
  {
    type: "Status",
    categories: ["Umum", "Tertutup", "Khusus"],
  },
];

const eventsData = [
  {
    title: "Staff Semarak Apresiasi",
    logo: "/placeholders/logo-event.webp",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    status: "Dibuka",
    startedAt: new Date("2025-08-11"),
    closedAt: new Date("2025-08-21"),
    categories: ["Umum", "Pra-Kampus"],
    isSaved: false,
  },
  {
    title: "Staff SUS",
    logo: "/placeholders/logo-event.webp",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    status: "Akan Datang",
    startedAt: new Date("2025-08-12"),
    closedAt: new Date("2025-08-21"),
    categories: ["Universitas", "Kepanitiaan", "Umum"],
    isSaved: false,
  },
  {
    title: "Staff Bahlil",
    logo: "/placeholders/logo-event.webp",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    status: "Ditutup",
    startedAt: new Date("2025-08-13"),
    closedAt: new Date("2025-08-21"),
    categories: ["Universitas", "Kepanitiaan", "Umum"],
    isSaved: false,
  },
  {
    title: "Staff Kreatif",
    logo: "/placeholders/logo-event.webp",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    status: "Dibuka",
    startedAt: new Date("2025-08-14"),
    closedAt: new Date("2025-08-24"),
    categories: ["Tertutup", "UKM"],
    isSaved: false,
  },
  {
    title: "Staff Inovasi",
    logo: "/placeholders/logo-event.webp",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    status: "Akan Datang",
    startedAt: new Date("2025-08-15"),
    closedAt: new Date("2025-08-25"),
    categories: ["Universitas", "Organisasi"],
    isSaved: false,
  },
  {
    title: "Staff Inspirasi",
    logo: "/placeholders/logo-event.webp",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    status: "Ditutup",
    startedAt: new Date("2025-08-16"),
    closedAt: new Date("2025-08-26"),
    categories: ["Khusus", "Kepanitiaan"],
    isSaved: false,
  },
  {
    title: "Staff Prestasi",
    logo: "/placeholders/logo-event.webp",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    status: "Dibuka",
    startedAt: new Date("2025-08-17"),
    closedAt: new Date("2025-08-27"),
    categories: ["Umum", "UKM"],
    isSaved: false,
  },
  {
    title: "Staff Semangat",
    logo: "/placeholders/logo-event.webp",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    status: "Akan Datang",
    startedAt: new Date("2025-08-18"),
    closedAt: new Date("2025-08-28"),
    categories: ["Universitas", "Pra-Kampus"],
    isSaved: false,
  },
  {
    title: "Staff Kreator",
    logo: "/placeholders/logo-event.webp",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    status: "Ditutup",
    startedAt: new Date("2025-08-19"),
    closedAt: new Date("2025-08-29"),
    categories: ["Organisasi", "Tertutup"],
    isSaved: false,
  },
  {
    title: "Staff Visioner",
    logo: "/placeholders/logo-event.webp",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    status: "Dibuka",
    startedAt: new Date("2025-08-20"),
    closedAt: new Date("2025-08-30"),
    categories: ["Kepanitiaan", "Khusus"],
    isSaved: false,
  },
  {
    title: "Staff Kreativitas",
    logo: "/placeholders/logo-event.webp",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    status: "Akan Datang",
    startedAt: new Date("2025-08-21"),
    closedAt: new Date("2025-08-31"),
    categories: ["Universitas", "UKM"],
    isSaved: false,
  },
  {
    title: "Staff Aksi",
    logo: "/placeholders/logo-event.webp",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    status: "Ditutup",
    startedAt: new Date("2025-08-22"),
    closedAt: new Date("2025-09-01"),
    categories: ["Umum", "Pra-Kampus"],
    isSaved: false,
  },
  {
    title: "Staff Hebat",
    logo: "/placeholders/logo-event.webp",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    status: "Dibuka",
    startedAt: new Date("2025-08-23"),
    closedAt: new Date("2025-09-02"),
    categories: ["Kepanitiaan", "Organisasi"],
    isSaved: false,
  },
  {
    title: "Staff Unggul",
    logo: "/placeholders/logo-event.webp",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    status: "Akan Datang",
    startedAt: new Date("2025-08-24"),
    closedAt: new Date("2025-09-03"),
    categories: ["Universitas", "Khusus"],
    isSaved: false,
  },
  {
    title: "Staff Vision",
    logo: "/placeholders/logo-event.webp",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    status: "Ditutup",
    startedAt: new Date("2025-08-25"),
    closedAt: new Date("2025-09-04"),
    categories: ["Tertutup", "UKM"],
    isSaved: false,
  },
  {
    title: "Staff Pioneer",
    logo: "/placeholders/logo-event.webp",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    status: "Dibuka",
    startedAt: new Date("2025-08-26"),
    closedAt: new Date("2025-09-05"),
    categories: ["Umum", "Kepanitiaan"],
    isSaved: false,
  },
  {
    title: "Staff Champion",
    logo: "/placeholders/logo-event.webp",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    status: "Akan Datang",
    startedAt: new Date("2025-08-27"),
    closedAt: new Date("2025-09-06"),
    categories: ["Universitas", "Organisasi"],
    isSaved: false,
  },
  {
    title: "Staff Kreator Hebat",
    logo: "/placeholders/logo-event.webp",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    status: "Ditutup",
    startedAt: new Date("2025-08-28"),
    closedAt: new Date("2025-09-07"),
    categories: ["Kepanitiaan", "Khusus"],
    isSaved: false,
  },
  {
    title: "Staff Inspiratif",
    logo: "/placeholders/logo-event.webp",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    status: "Dibuka",
    startedAt: new Date("2025-08-29"),
    closedAt: new Date("2025-09-08"),
    categories: ["Tertutup", "Pra-Kampus"],
    isSaved: false,
  },
  {
    title: "Staff Kreatif Muda",
    logo: "/placeholders/logo-event.webp",
    desc: "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
    status: "Akan Datang",
    startedAt: new Date("2025-08-30"),
    closedAt: new Date("2025-09-09"),
    categories: ["Universitas", "UKM"],
    isSaved: false,
  },
] as const;

export { filterCategory, eventsData };
